# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
"""
module9/config/corpora.py
==========================
The three DevOps Companion corpora from the Module 9 worked example
(v5 Section 10): service, policy, and history.

Each corpus carries a Module 5 CorpusConfig (the Bedrock Knowledge Base
seam declared on DomainConfig) plus the pipeline-facing attributes the
ingestion stages need: chunking strategy (v5 Appendix A), freshness SLA
(v5 Section 9.2), and access-control stamps (v5 Section 7 and Appendix B).

The live demo ingests into the history corpus, whose content is generated
by the agent system itself (v5 Section 10.3). Service and policy are
represented with seed data so the three-corpus story is complete.
"""
from __future__ import annotations

from dataclasses import dataclass, field

from module5.engine.domain_adapter import CorpusConfig


@dataclass(frozen=True)
class CorpusSpec:
    """Pipeline configuration for one knowledge corpus.

    Parameters
    ----------
    name : str
        Corpus identifier: 'service', 'policy', or 'history'. Written to
        every chunk as the `corpus` and `domain` metadata fields.
    description : str
        One-line purpose statement, also used in CorpusConfig.
    chunking_strategy : str
        Appendix B enum: 'fixed', 'semantic', or 'hierarchical-child'
        (parents are stamped 'hierarchical-parent' at chunk time).
    freshness_sla_hours : float
        Maximum acceptable age of the newest chunk before the corpus is
        flagged stale (v5 Section 9.2 end-to-end freshness monitoring).
    access_level : str
        Appendix B enum: 'public', 'internal', or 'sensitive'.
    allowed_agent_roles : tuple[str, ...]
        Agent role name suffixes permitted to retrieve from this corpus.
    agent_scope : str
        Scalar row-level-security stamp applied to every chunk and compiled
        into the retrieval filter_dict (v5 Section 10.3 uses
        agent_scope: operations for the history corpus).
    corpus_config : CorpusConfig
        The Module 5 Bedrock Knowledge Base seam, populated so the
        DomainConfig story carries through even though the runnable sink
        is the Module 7 MongoStore.
    """

    name: str
    description: str
    chunking_strategy: str
    freshness_sla_hours: float
    access_level: str
    allowed_agent_roles: tuple[str, ...]
    agent_scope: str
    corpus_config: CorpusConfig = field(default=None)  # type: ignore[assignment]


def _corpus_config(description: str, chunking: str) -> CorpusConfig:
    return CorpusConfig(
        knowledge_base_id=None,  # populated when a Bedrock KB is provisioned
        description=description,
        chunking_strategy=chunking,
        embedding_model="amazon.titan-embed-text-v2:0",
    )


SERVICE_CORPUS = CorpusSpec(
    name="service",
    description=(
        "AWS service documentation, CDK construct reference, EKS configuration "
        "patterns, and CloudWatch alarm templates. Weekly refresh."
    ),
    chunking_strategy="hierarchical-child",
    freshness_sla_hours=192.0,  # 8 days: catches a failed Sunday job (Section 10.1)
    access_level="internal",
    allowed_agent_roles=(
        "Orchestrator",
        "RepositoryAnalysis",
        "InfrastructureGeneration",
        "DeployObserve",
    ),
    agent_scope="general",
    corpus_config=_corpus_config(
        "DevOps Companion service corpus: AWS docs and construct reference.",
        "HIERARCHICAL",
    ),
)

POLICY_CORPUS = CorpusSpec(
    name="policy",
    description=(
        "Deployment runbooks, security requirements, approved IaC patterns, "
        "and coding standards. Event-driven refresh, under 10 minutes of lag."
    ),
    chunking_strategy="semantic",
    freshness_sla_hours=24.0,
    access_level="internal",
    allowed_agent_roles=(
        "Orchestrator",
        "RepositoryAnalysis",
        "InfrastructureGeneration",
        "DeployObserve",
    ),
    agent_scope="general",
    corpus_config=_corpus_config(
        "DevOps Companion policy corpus: runbooks and security requirements.",
        "SEMANTIC",
    ),
)

HISTORY_CORPUS = CorpusSpec(
    name="history",
    description=(
        "Deployment and incident records generated by the agent system itself. "
        "Streamed through Confluent, landed in Delta Lake, refreshed nightly."
    ),
    chunking_strategy="fixed",
    freshness_sla_hours=26.0,  # nightly refresh plus margin (Section 10.3)
    access_level="internal",
    allowed_agent_roles=("Orchestrator", "DeployObserve"),
    agent_scope="operations",
    corpus_config=_corpus_config(
        "DevOps Companion history corpus: past deployments and incidents.",
        "FIXED_SIZE",
    ),
)

CORPORA: dict[str, CorpusSpec] = {
    "service": SERVICE_CORPUS,
    "policy": POLICY_CORPUS,
    "history": HISTORY_CORPUS,
}

VALID_CORPUS_NAMES = frozenset(CORPORA)


def get_corpus(name: str) -> CorpusSpec:
    """Return the CorpusSpec for a corpus name, raising on unknown names."""
    if name not in CORPORA:
        raise ValueError(
            f"Unknown corpus {name!r}. Valid corpora: {sorted(CORPORA)}"
        )
    return CORPORA[name]
